package com.cmpt276.lota.sudoku;

import com.cmpt276.lota.sudoku.model.Words;

import org.junit.Before;
import org.junit.Test;

import java.util.UUID;

import static org.junit.Assert.*;

public class WordsTest {
    private Words testWord;

    @Before
    public void setUp() throws Exception {
        testWord = new Words("test1","test2");
    }

    @Test
    public void getId()
    {
        UUID ID = testWord.getId();
        assertNotEquals(null,testWord.getId());
        //not a good way since UUID is generated by the library function
    }

    @Test
    public void getLanguageOne()
    {
        assertEquals("test1",testWord.getLanguageOne());
    }

    @Test
    public void setLanguageOne()
    {
        testWord.setLanguageOne("testSet1");
        assertNotEquals("test1",testWord.getLanguageOne());
        assertEquals("testSet1",testWord.getLanguageOne());
        assertNotEquals(null,testWord.getLanguageOne());
        testWord.setLanguageOne("test1");
    }

    @Test
    public void getLanguageTwo()
    {
        assertEquals("test2",testWord.getLanguageTwo());
        assertNotEquals("test",testWord.getLanguageTwo());
        assertNotEquals(null,testWord.getLanguageTwo());
    }

    @Test
    public void setLanguageTwo()
    {
        testWord.setLanguageTwo("testSet2");
        assertNotEquals("test2",testWord.getLanguageTwo());
        assertEquals("testSet2",testWord.getLanguageTwo());
        testWord.setLanguageTwo("test2");
        assertNotEquals(null,testWord.getLanguageTwo());
    }
}